config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'welcome#index'

  get 'pagestest5/show'

  get 'pagestest5/edit'

  get 'pagestest5/destroy'

  get 'pagestest4/index'

  resources :posts
  #get 'posts' => 'posts#show'
  #get 'posts/new' => 'posts#new'
  #post 'posts' => 'posts#create'

  # this says go to about controller and go to this method in the controller
  get 'about' => 'about#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'aboutshow' => 'about#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  @myabouttext = 'This is from the about controller!'
  end

  def show
    @myaboutshowtext = 'This is from the about show method.'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/pagestest4_controller.rb
class Pagestest4Controller < ApplicationController
    def index 
    end
end

app/controllers/pagestest5_controller.rb
class Pagestest5Controller < ApplicationController
  def show
  end

  def edit
  end

  def destroy
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:firstname, :lastname, :age)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @allposts=Post.all
  end

  def index
    @allposts=Post.all
  end

  # we are creating a new instance variable when we go 
  # to our posts web page form
  def new
    @post = Post.new
  end
  # we are submitting - which comes into create 
  # calls the page_params method when we create 
  # another instance of a post object but filled with 
  #data. If saves - directs to posts, otherwise sends us to new
  def create
    @post = Post.new(page_params)
    if @post.save
        redirect_to '/posts'
    else
      render 'new'
    end
    end

    private
    def page_params
      params.require(:post).permit(:posttext, :postauthor)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pagestest4_helper.rb
module Pagestest4Helper
end

app/helpers/pagestest5_helper.rb
module Pagestest5Helper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<% provide(:title, "About") %>

<h1>This is the about page!</h1>
<p>Find me in app/views/about/index.html.erb</p>
	<p><%= @myabouttext %></p>
    <%= render '/layouts/partial' %>

app/views/about/show.html.erb
<% provide(:title, "About - Show") %>
<p>This is the about show view.</p>
<p><%= @myaboutshowtext%>

app/views/layouts/_partial.html.erb
<p>This is a partial.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> | Project 3 </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pagestest4/index.html.erb
<% provide(:title, "PagesTest4") %>

<h1>This is pagestest4</h1>

app/views/pagestest5/destroy.html.erb
<h1>Pagestest5#destroy</h1>
<p>Find me in app/views/pagestest5/destroy.html.erb</p>

app/views/pagestest5/edit.html.erb
<h1>Pagestest5#edit</h1>
<p>Find me in app/views/pagestest5/edit.html.erb</p>

app/views/pagestest5/show.html.erb
<h1>Pagestest5#show</h1>
<p>Find me in app/views/pagestest5/show.html.erb</p>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :person_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :person_lastname %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :person_age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.firstname %></td>
        <td><%= person.lastname %></td>
        <td><%= person.age %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @person.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @person.lastname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Posts</p>
<% @allposts.each do |post| %>
<%= post.posttext %> <br>
<% end %>

app/views/posts/new.html.erb
<p>Submit a new post</p>
<%= form_for(@post) do |f| %>
<div class="field">
    <%= f.label :'Post Text' %> <br>
    <%= f.text_area :posttext %> <br>
    <%= f.label :'Post Author' %> <br>
    <%= f.text_field :postauthor %> <br>
</div>
<div>
    <%= f.submit 'Create' %>
</div>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Posts</p>
<% @allposts.each do |post| %>
<%= post.posttext %> <br>
<% end %>

app/views/welcome/index.html.erb
<% provide(:title, "Home") %>
<h1>Welcome to my rails website!</h1>

<p>Go here for the <%= link_to 'about page', about_path %></p>
<p>Go here for the <%= link_to 'Show all people', people_path %></p>
<p>Go here for the <%= link_to 'Add new person', new_person_path %></p>

<p>Go here for the <%= link_to 'pages test', pagestest4_index_path %></p>
		